name: build_and_release #名称随意
on:
  push: #设置触发规则
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix: # 会分开成两个任务分别执行
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code #这部分是为了从github自动clone代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Go env prepare
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
          check-latest: true

      - name: Run unix build
        if:  matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          ./build.sh
          tar -zcvf qiniuserver-${{ matrix.os }}.tar.gz ./qiniuserver ./assert ./config ./LICENSE
          curl https://raw.githubusercontent.com/chenxuan520/gh-action-shell/main/git_commit_message_from_last_tag.sh | bash 1>commit-message.log 2>/dev/null

      - name: Run windows build
        if: matrix.os == 'windows-latest'
        run: |
          cd ./src
          go build .
          mv ./qiniuserver.exe ..
          cd ..
          tar -zcvf qiniuserver-${{ matrix.os }}.tar.gz ./qiniuserver.exe ./assert ./config ./LICENSE

      - name: Unix Release
        uses: softprops/action-gh-release@v2
        if: ( matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' ) && startsWith(github.ref, 'refs/tags/')
        with:
          body_path: commit-message.log
          files: |
            qiniuserver-${{ matrix.os }}.tar.gz
            LICENSE

      - name: Windows Release
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qiniuserver-${{ matrix.os }}.tar.gz
